# Generated by Django 4.1.2 on 2023-04-22 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Danger_Zones',
            fields=[
                ('zone_id', models.IntegerField(primary_key=True, serialize=False)),
                ('file_location', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Dependents',
            fields=[
                ('dependent_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('is_cat', models.BooleanField()),
                ('breed', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feeding_Schedule',
            fields=[
                ('cron_schedule', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('is_currently_used', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Potential_Emergencies',
            fields=[
                ('emer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('occurrence', models.DateTimeField()),
                ('is_true', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Saved_Sounds',
            fields=[
                ('sound_id', models.IntegerField(primary_key=True, serialize=False)),
                ('sound_name', models.CharField(max_length=255)),
                ('sound_size', models.IntegerField()),
                ('sound_length', models.IntegerField()),
                ('sound_location', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Users_dependents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dependent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artemis.dependents')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artemis.users')),
            ],
        ),
        migrations.CreateModel(
            name='Sensor_Data',
            fields=[
                ('timestamp_id', models.DateTimeField(primary_key=True, serialize=False)),
                ('sound_sensor', models.IntegerField()),
                ('thermal_sensor', models.IntegerField()),
                ('is_asleep', models.BooleanField()),
                ('dependent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artemis.dependents')),
            ],
        ),
        migrations.CreateModel(
            name='Medical_History',
            fields=[
                ('event_id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=255)),
                ('dependent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artemis.dependents')),
            ],
        ),
    ]
