# Generated by Django 4.1.2 on 2023-04-22 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artemis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dependents',
            name='dependents',
            field=models.ManyToManyField(related_name='models', through='artemis.Users_dependents', to='artemis.users'),
        ),
    ]
