# Generated by Django 4.1.2 on 2023-04-22 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artemis', '0002_dependents_dependents'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dependents',
            old_name='dependents',
            new_name='users',
        ),
    ]
