# Generated by Django 4.1.2 on 2023-04-22 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artemis', '0003_rename_dependents_dependents_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dependents',
            name='users',
        ),
        migrations.AddField(
            model_name='dependents',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='artemis.users'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Users_dependents',
        ),
    ]
