# Generated by Django 4.1.2 on 2023-04-22 19:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('artemis', '0004_remove_dependents_users_dependents_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saved_sounds',
            name='sound_file',
            field=models.FileField(default=1, upload_to='documents/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saved_sounds',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='saved_sounds',
            name='sound_location',
            field=models.CharField(default='documents/', max_length=255),
        ),
    ]
